// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Business.wsgestaomaterial.seplag.ce.gov.br {
    
    
    /// <remarks/>
    [System.Web.Services.WebServiceBinding(Name="wsgestaomaterial", Namespace="http://wsgestaomaterial.seplag.ce.gov.br/wsgestaomaterial/services/wsgestaomaterial")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapInclude(typeof(Vector))]
    public partial class GestaoMaterialFacadeService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getVwDadosWebServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaItemPorQualquerPalavraOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaItemPorTodasPalavrasOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaItemPorExpressaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaItemPorCodigoOperationCompleted;
        
        public GestaoMaterialFacadeService() {
            this.Url = "http://wsgestaomaterial.seplag.ce.gov.br/wsgestaomaterial/services/wsgestaomaterial";
        }
        
        public GestaoMaterialFacadeService(string url) {
            this.Url = url;
        }
        
        public event getVwDadosWebServiceCompletedEventHandler getVwDadosWebServiceCompleted;
        
        public event consultaItemPorQualquerPalavraCompletedEventHandler consultaItemPorQualquerPalavraCompleted;
        
        public event consultaItemPorTodasPalavrasCompletedEventHandler consultaItemPorTodasPalavrasCompleted;
        
        public event consultaItemPorExpressaoCompletedEventHandler consultaItemPorExpressaoCompleted;
        
        public event consultaItemPorCodigoCompletedEventHandler consultaItemPorCodigoCompleted;
        
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://facade.wsgestaomaterial.seplag.ce.gov.br", ResponseNamespace="http://wsgestaomaterial.seplag.ce.gov.br/wsgestaomaterial/services/wsgestaomaterial")]
        [return: System.Xml.Serialization.SoapElement("getVwDadosWebServiceReturn")]
        public VwDadosWebService getVwDadosWebService() {
            object[] results = this.Invoke("getVwDadosWebService", new object[0]);
            return ((VwDadosWebService)(results[0]));
        }
        
        public System.IAsyncResult BegingetVwDadosWebService(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getVwDadosWebService", new object[0], callback, asyncState);
        }
        
        public VwDadosWebService EndgetVwDadosWebService(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((VwDadosWebService)(results[0]));
        }
        
        public void getVwDadosWebServiceAsync() {
            this.getVwDadosWebServiceAsync(null);
        }
        
        public void getVwDadosWebServiceAsync(object userState) {
            if ((this.getVwDadosWebServiceOperationCompleted == null)) {
                this.getVwDadosWebServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVwDadosWebServiceCompleted);
            }
            this.InvokeAsync("getVwDadosWebService", new object[0], this.getVwDadosWebServiceOperationCompleted, userState);
        }
        
        private void OngetVwDadosWebServiceCompleted(object arg) {
            if ((this.getVwDadosWebServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVwDadosWebServiceCompleted(this, new getVwDadosWebServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://facade.wsgestaomaterial.seplag.ce.gov.br", ResponseNamespace="http://wsgestaomaterial.seplag.ce.gov.br/wsgestaomaterial/services/wsgestaomaterial")]
        [return: System.Xml.Serialization.SoapElement("consultaItemPorQualquerPalavraReturn")]
        public object[] consultaItemPorQualquerPalavra(string palavrasDigitadas) {
            object[] results = this.Invoke("consultaItemPorQualquerPalavra", new object[] {
                        palavrasDigitadas});
            return ((object[])(results[0]));
        }
        
        public System.IAsyncResult BeginconsultaItemPorQualquerPalavra(string palavrasDigitadas, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("consultaItemPorQualquerPalavra", new object[] {
                        palavrasDigitadas}, callback, asyncState);
        }
        
        public object[] EndconsultaItemPorQualquerPalavra(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        public void consultaItemPorQualquerPalavraAsync(string palavrasDigitadas) {
            this.consultaItemPorQualquerPalavraAsync(palavrasDigitadas, null);
        }
        
        public void consultaItemPorQualquerPalavraAsync(string palavrasDigitadas, object userState) {
            if ((this.consultaItemPorQualquerPalavraOperationCompleted == null)) {
                this.consultaItemPorQualquerPalavraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaItemPorQualquerPalavraCompleted);
            }
            this.InvokeAsync("consultaItemPorQualquerPalavra", new object[] {
                        palavrasDigitadas}, this.consultaItemPorQualquerPalavraOperationCompleted, userState);
        }
        
        private void OnconsultaItemPorQualquerPalavraCompleted(object arg) {
            if ((this.consultaItemPorQualquerPalavraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaItemPorQualquerPalavraCompleted(this, new consultaItemPorQualquerPalavraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://facade.wsgestaomaterial.seplag.ce.gov.br", ResponseNamespace="http://wsgestaomaterial.seplag.ce.gov.br/wsgestaomaterial/services/wsgestaomaterial")]
        [return: System.Xml.Serialization.SoapElement("consultaItemPorTodasPalavrasReturn")]
        public object[] consultaItemPorTodasPalavras(string palavrasDigitadas) {
            object[] results = this.Invoke("consultaItemPorTodasPalavras", new object[] {
                        palavrasDigitadas});
            return ((object[])(results[0]));
        }
        
        public System.IAsyncResult BeginconsultaItemPorTodasPalavras(string palavrasDigitadas, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("consultaItemPorTodasPalavras", new object[] {
                        palavrasDigitadas}, callback, asyncState);
        }
        
        public object[] EndconsultaItemPorTodasPalavras(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        public void consultaItemPorTodasPalavrasAsync(string palavrasDigitadas) {
            this.consultaItemPorTodasPalavrasAsync(palavrasDigitadas, null);
        }
        
        public void consultaItemPorTodasPalavrasAsync(string palavrasDigitadas, object userState) {
            if ((this.consultaItemPorTodasPalavrasOperationCompleted == null)) {
                this.consultaItemPorTodasPalavrasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaItemPorTodasPalavrasCompleted);
            }
            this.InvokeAsync("consultaItemPorTodasPalavras", new object[] {
                        palavrasDigitadas}, this.consultaItemPorTodasPalavrasOperationCompleted, userState);
        }
        
        private void OnconsultaItemPorTodasPalavrasCompleted(object arg) {
            if ((this.consultaItemPorTodasPalavrasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaItemPorTodasPalavrasCompleted(this, new consultaItemPorTodasPalavrasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://facade.wsgestaomaterial.seplag.ce.gov.br", ResponseNamespace="http://wsgestaomaterial.seplag.ce.gov.br/wsgestaomaterial/services/wsgestaomaterial")]
        [return: System.Xml.Serialization.SoapElement("consultaItemPorExpressaoReturn")]
        public object[] consultaItemPorExpressao(string expressaoDigitada) {
            object[] results = this.Invoke("consultaItemPorExpressao", new object[] {
                        expressaoDigitada});
            return ((object[])(results[0]));
        }
        
        public System.IAsyncResult BeginconsultaItemPorExpressao(string expressaoDigitada, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("consultaItemPorExpressao", new object[] {
                        expressaoDigitada}, callback, asyncState);
        }
        
        public object[] EndconsultaItemPorExpressao(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        public void consultaItemPorExpressaoAsync(string expressaoDigitada) {
            this.consultaItemPorExpressaoAsync(expressaoDigitada, null);
        }
        
        public void consultaItemPorExpressaoAsync(string expressaoDigitada, object userState) {
            if ((this.consultaItemPorExpressaoOperationCompleted == null)) {
                this.consultaItemPorExpressaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaItemPorExpressaoCompleted);
            }
            this.InvokeAsync("consultaItemPorExpressao", new object[] {
                        expressaoDigitada}, this.consultaItemPorExpressaoOperationCompleted, userState);
        }
        
        private void OnconsultaItemPorExpressaoCompleted(object arg) {
            if ((this.consultaItemPorExpressaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaItemPorExpressaoCompleted(this, new consultaItemPorExpressaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://facade.wsgestaomaterial.seplag.ce.gov.br", ResponseNamespace="http://wsgestaomaterial.seplag.ce.gov.br/wsgestaomaterial/services/wsgestaomaterial")]
        [return: System.Xml.Serialization.SoapElement("consultaItemPorCodigoReturn")]
        public object[] consultaItemPorCodigo(int codigoItem) {
            object[] results = this.Invoke("consultaItemPorCodigo", new object[] {
                        codigoItem});
            return ((object[])(results[0]));
        }
        
        public System.IAsyncResult BeginconsultaItemPorCodigo(int codigoItem, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("consultaItemPorCodigo", new object[] {
                        codigoItem}, callback, asyncState);
        }
        
        public object[] EndconsultaItemPorCodigo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        public void consultaItemPorCodigoAsync(int codigoItem) {
            this.consultaItemPorCodigoAsync(codigoItem, null);
        }
        
        public void consultaItemPorCodigoAsync(int codigoItem, object userState) {
            if ((this.consultaItemPorCodigoOperationCompleted == null)) {
                this.consultaItemPorCodigoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaItemPorCodigoCompleted);
            }
            this.InvokeAsync("consultaItemPorCodigo", new object[] {
                        codigoItem}, this.consultaItemPorCodigoOperationCompleted, userState);
        }
        
        private void OnconsultaItemPorCodigoCompleted(object arg) {
            if ((this.consultaItemPorCodigoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaItemPorCodigoCompleted(this, new consultaItemPorCodigoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapType(Namespace="urn:bean.local")]
    public partial class VwDadosWebService {
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElement(DataType="decimal")]
        public System.Nullable<decimal> codigoCategoria;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElement(DataType="decimal")]
        public System.Nullable<decimal> codigoClasse;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElement(DataType="decimal")]
        public System.Nullable<decimal> codigoGrupo;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElement(DataType="decimal")]
        public System.Nullable<decimal> codigoItem;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElement(DataType="decimal")]
        public System.Nullable<decimal> codigoMaterial;
        
        /// <remarks/>
        public string descricaoItem;
        
        /// <remarks/>
        public string nomeCategoria;
        
        /// <remarks/>
        public string nomeClasse;
        
        /// <remarks/>
        public string nomeGrupo;
        
        /// <remarks/>
        public string nomeMaterial;
        
        /// <remarks/>
        public string tipoCategoria;
        
        /// <remarks/>
        public string unidadeFornecimento;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapType(Namespace="http://xml.apache.org/xml-soap")]
    public partial class Vector {
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElement("item")]
        public object[] item;
    }
    
    public partial class getVwDadosWebServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVwDadosWebServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public VwDadosWebService Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VwDadosWebService)(this.results[0]));
            }
        }
    }
    
    public delegate void getVwDadosWebServiceCompletedEventHandler(object sender, getVwDadosWebServiceCompletedEventArgs args);
    
    public partial class consultaItemPorQualquerPalavraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaItemPorQualquerPalavraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    public delegate void consultaItemPorQualquerPalavraCompletedEventHandler(object sender, consultaItemPorQualquerPalavraCompletedEventArgs args);
    
    public partial class consultaItemPorTodasPalavrasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaItemPorTodasPalavrasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    public delegate void consultaItemPorTodasPalavrasCompletedEventHandler(object sender, consultaItemPorTodasPalavrasCompletedEventArgs args);
    
    public partial class consultaItemPorExpressaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaItemPorExpressaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    public delegate void consultaItemPorExpressaoCompletedEventHandler(object sender, consultaItemPorExpressaoCompletedEventArgs args);
    
    public partial class consultaItemPorCodigoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaItemPorCodigoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    public delegate void consultaItemPorCodigoCompletedEventHandler(object sender, consultaItemPorCodigoCompletedEventArgs args);
}
